using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;

namespace WpfApp1.Services
{
    public static class FieldMatcherService
    {
        private static readonly string[] DefaultPrefixes = ["zjb_", "tmp_", "mid_", "src_"];
        private static readonly string[] DefaultSuffixes = ["_text", "_str", "_value"];

        private static readonly string[] AutoGeneratedUuidNames = ["id", "baid"];
        private static readonly string[] AutoGeneratedUuidSuffixes = ["uuid", "guid"];

        /// <summary>
        /// Auto-generate field mapping suggestions.
        /// The matcher works in stages so exact and semantically safe matches
        /// are claimed first, while risky fuzzy matches are kept as a last resort.
        /// </summary>
        public static List<DvMappingRow> AutoMap(
            IReadOnlyList<DvTargetColumn> targets,
            IReadOnlyList<string> sourceHeaders)
        {
            var sourceInfos = sourceHeaders
                .Select((name, index) => new SourceField(index, name, AnalyzeField(name)))
                .ToList();

            var targetInfos = targets
                .Select((target, index) => CreateTargetField(target, index, sourceInfos))
                .ToList();

            var decisions = new MatchDecision?[targets.Count];
            var usedSources = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

            AssignExactMatches(targetInfos, sourceInfos, usedSources, decisions);
            AssignNormalizedMatches(targetInfos, sourceInfos, usedSources, decisions);
            AssignStrippedMatches(targetInfos, sourceInfos, usedSources, decisions);
            AssignSemanticMatches(targetInfos, sourceInfos, usedSources, decisions);
            AssignLowConfidenceMatches(targetInfos, sourceInfos, usedSources, decisions);

            var result = new List<DvMappingRow>(targets.Count);
            for (int i = 0; i < targetInfos.Count; i++)
            {
                var targetInfo = targetInfos[i];
                var decision = decisions[i];
                bool isUuidTarget = targetInfo.Target.NormalizedType == DvNormalizedType.Guid;
                bool isAutoGen = IsAutoGeneratedUuidCandidate(targetInfo.Target, sourceHeaders, decision?.Source);

                var row = new DvMappingRow
                {
                    RowIndex = i + 1,
                    TargetColumnName = targetInfo.Target.ColumnName,
                    TargetDisplayType = targetInfo.Target.DisplayType,
                    IsRequired = !targetInfo.Target.IsNullable,
                    IsUuidTarget = isUuidTarget,
                    IsAutoGenCandidate = isAutoGen
                };

                if (decision is MatchDecision match)
                {
                    row.MappingType = DvMappingType.Source;
                    row.SourceColumnName = match.Source;
                    row.MatchMethod = match.Method;
                    row.Confidence = match.Confidence;
                    row.MatchReason = isUuidTarget
                        ? BuildUuidManualReason(match.Reason, hasSuggestedSource: true)
                        : match.Reason;
                    row.NeedsConfirmation = isUuidTarget || match.NeedsConfirmation;
                    row.IsConfirmed = isUuidTarget ? false : !match.NeedsConfirmation;
                    row.WasAutoIgnored = false;
                }
                else
                {
                    row.MappingType = DvMappingType.Ignore;
                    row.MatchMethod = DvMatchMethod.Manual;
                    row.Confidence = 0;
                    row.MatchReason = isUuidTarget
                        ? BuildUuidManualReason(BuildNoMatchReason(targetInfo, isAutoGen), hasSuggestedSource: false)
                        : BuildNoMatchReason(targetInfo, isAutoGen);
                    row.NeedsConfirmation = isUuidTarget;
                    row.IsConfirmed = isUuidTarget ? false : isAutoGen || targetInfo.Target.IsNullable;
                    row.WasAutoIgnored = true;
                }

                result.Add(row);
            }

            return result;
        }

        private static void AssignExactMatches(
            IReadOnlyList<TargetField> targets,
            IReadOnlyList<SourceField> sources,
            ISet<string> usedSources,
            MatchDecision?[] decisions)
        {
            foreach (var target in targets)
            {
                if (decisions[target.Index] != null)
                    continue;

                var candidate = sources.FirstOrDefault(source =>
                    !usedSources.Contains(source.Name) &&
                    string.Equals(source.Name, target.Target.ColumnName, StringComparison.OrdinalIgnoreCase));

                if (candidate.Name == null)
                    continue;

                decisions[target.Index] = new MatchDecision(
                    candidate.Name,
                    DvMatchMethod.Exact,
                    100,
                    "字段名完全一致",
                    NeedsConfirmation: false);

                usedSources.Add(candidate.Name);
            }
        }

        private static void AssignNormalizedMatches(
            IReadOnlyList<TargetField> targets,
            IReadOnlyList<SourceField> sources,
            ISet<string> usedSources,
            MatchDecision?[] decisions)
        {
            foreach (var target in targets)
            {
                if (decisions[target.Index] != null)
                    continue;

                var candidates = sources
                    .Where(source =>
                        !usedSources.Contains(source.Name) &&
                        source.Info.NormalizedName == target.Info.NormalizedName)
                    .OrderBy(source => source.Index)
                    .ToList();

                if (candidates.Count == 0)
                    continue;

                var chosen = candidates[0];
                decisions[target.Index] = new MatchDecision(
                    chosen.Name,
                    DvMatchMethod.Normalized,
                    95,
                    "去除大小写和分隔符差异后命中",
                    NeedsConfirmation: false);

                usedSources.Add(chosen.Name);
            }
        }

        private static void AssignStrippedMatches(
            IReadOnlyList<TargetField> targets,
            IReadOnlyList<SourceField> sources,
            ISet<string> usedSources,
            MatchDecision?[] decisions)
        {
            foreach (var target in targets)
            {
                if (decisions[target.Index] != null)
                    continue;

                var candidates = sources
                    .Where(source =>
                        !usedSources.Contains(source.Name) &&
                        source.Info.StrippedNormalizedName == target.Info.StrippedNormalizedName &&
                        IsStrippedMatchCompatible(target, source))
                    .OrderByDescending(source => GetStrippedPriority(target, source))
                    .ThenBy(source => source.Index)
                    .ToList();

                if (candidates.Count == 0)
                    continue;

                var chosen = candidates[0];
                decisions[target.Index] = new MatchDecision(
                    chosen.Name,
                    DvMatchMethod.PrefixStrip,
                    90,
                    "去除系统前后缀后命中",
                    NeedsConfirmation: false);

                usedSources.Add(chosen.Name);
            }
        }

        private static void AssignSemanticMatches(
            IReadOnlyList<TargetField> targets,
            IReadOnlyList<SourceField> sources,
            ISet<string> usedSources,
            MatchDecision?[] decisions)
        {
            foreach (var target in targets)
            {
                if (decisions[target.Index] != null)
                    continue;

                var candidates = sources
                    .Where(source =>
                        !usedSources.Contains(source.Name) &&
                        source.Info.BaseName == target.Info.BaseName &&
                        IsStrongSemanticCompatible(target, source))
                    .OrderByDescending(source => GetSemanticScore(target, source))
                    .ThenBy(source => source.Index)
                    .ToList();

                if (candidates.Count == 0)
                    continue;

                var chosen = candidates[0];
                decisions[target.Index] = new MatchDecision(
                    chosen.Name,
                    DvMatchMethod.Semantic,
                    GetSemanticScore(target, chosen),
                    BuildSemanticReason(target),
                    NeedsConfirmation: false);

                usedSources.Add(chosen.Name);
            }
        }

        private static void AssignLowConfidenceMatches(
            IReadOnlyList<TargetField> targets,
            IReadOnlyList<SourceField> sources,
            ISet<string> usedSources,
            MatchDecision?[] decisions)
        {
            foreach (var target in targets)
            {
                if (decisions[target.Index] != null)
                    continue;

                if (target.Target.NormalizedType == DvNormalizedType.Guid)
                    continue;

                var candidates = sources
                    .Where(source =>
                        !usedSources.Contains(source.Name) &&
                        IsLowConfidenceCompatible(target, source))
                    .Select(source => new
                    {
                        Source = source,
                        Score = GetLowConfidenceScore(target, source)
                    })
                    .Where(x => x.Score > 0)
                    .OrderByDescending(x => x.Score)
                    .ThenBy(x => x.Source.Index)
                    .ToList();

                if (candidates.Count == 0)
                    continue;

                var chosen = candidates[0];
                decisions[target.Index] = new MatchDecision(
                    chosen.Source.Name,
                    DvMatchMethod.Contains,
                    chosen.Score,
                    BuildLowConfidenceReason(target),
                    NeedsConfirmation: true);

                usedSources.Add(chosen.Source.Name);
            }
        }

        private static TargetField CreateTargetField(
            DvTargetColumn target,
            int index,
            IReadOnlyList<SourceField> sources)
        {
            var info = AnalyzeField(target.ColumnName);
            var sameBaseFamilies = sources
                .Where(source => source.Info.BaseName == info.BaseName)
                .Select(source => source.Info.Family)
                .Distinct()
                .ToHashSet();

            FieldSemanticFamily preferredFamily = InferPreferredFamily(target, info, sameBaseFamilies);
            return new TargetField(index, target, info, preferredFamily);
        }

        private static bool IsStrippedMatchCompatible(TargetField target, SourceField source)
        {
            if (target.Target.NormalizedType == DvNormalizedType.Guid)
            {
                return source.Info.Family is FieldSemanticFamily.Core or FieldSemanticFamily.Identifier;
            }

            if (target.Info.Family == FieldSemanticFamily.Description)
            {
                return source.Info.Family == FieldSemanticFamily.Description;
            }

            if (target.Info.Family == FieldSemanticFamily.ExternalCode)
            {
                return source.Info.Family == FieldSemanticFamily.ExternalCode;
            }

            return true;
        }

        private static int GetStrippedPriority(TargetField target, SourceField source)
        {
            int score = 80;

            if (source.Info.Family == target.PreferredFamily)
                score += 8;

            if (source.Info.Family == target.Info.Family)
                score += 5;

            if (source.Info.BaseName == target.Info.BaseName)
                score += 5;

            return score;
        }

        private static FieldSemanticFamily InferPreferredFamily(
            DvTargetColumn target,
            FieldSemanticInfo targetInfo,
            ISet<FieldSemanticFamily> sameBaseFamilies)
        {
            if (targetInfo.Family != FieldSemanticFamily.Core)
                return targetInfo.Family;

            if (target.NormalizedType == DvNormalizedType.Guid)
                return FieldSemanticFamily.Identifier;

            if (target.NormalizedType == DvNormalizedType.String)
            {
                if (sameBaseFamilies.Contains(FieldSemanticFamily.Name))
                    return FieldSemanticFamily.Name;

                if (sameBaseFamilies.Contains(FieldSemanticFamily.Description))
                    return FieldSemanticFamily.Description;
            }

            return FieldSemanticFamily.Core;
        }

        private static bool IsStrongSemanticCompatible(TargetField target, SourceField source)
        {
            if (target.Info.BaseName != source.Info.BaseName)
                return false;

            if (target.Target.NormalizedType == DvNormalizedType.Guid)
            {
                return source.Info.Family == FieldSemanticFamily.Identifier;
            }

            if (target.Info.Family == FieldSemanticFamily.Identifier)
            {
                return source.Info.Family == FieldSemanticFamily.Identifier;
            }

            if (target.Info.Family == FieldSemanticFamily.Name)
            {
                return source.Info.Family == FieldSemanticFamily.Name;
            }

            if (target.Info.Family == FieldSemanticFamily.Description)
            {
                return source.Info.Family == FieldSemanticFamily.Description;
            }

            if (target.Info.Family == FieldSemanticFamily.ExternalCode)
            {
                return source.Info.Family == FieldSemanticFamily.ExternalCode;
            }

            if (target.Target.NormalizedType == DvNormalizedType.String)
            {
                return source.Info.Family == target.PreferredFamily;
            }

            return source.Info.Family is FieldSemanticFamily.Core or FieldSemanticFamily.Identifier;
        }

        private static int GetSemanticScore(TargetField target, SourceField source)
        {
            int score = 84;

            if (target.Target.NormalizedType == DvNormalizedType.Guid &&
                source.Info.Family == FieldSemanticFamily.Identifier)
            {
                return 92;
            }

            if (source.Info.Family == target.PreferredFamily)
                score += 6;

            if (source.Info.Family == target.Info.Family)
                score += 3;

            return Math.Min(score, 92);
        }

        private static bool IsLowConfidenceCompatible(TargetField target, SourceField source)
        {
            if (target.Info.Family == FieldSemanticFamily.Description)
                return source.Info.Family == FieldSemanticFamily.Description;

            if (target.Info.Family == FieldSemanticFamily.Name)
                return source.Info.Family == FieldSemanticFamily.Name;

            if (target.Info.Family == FieldSemanticFamily.ExternalCode)
                return source.Info.Family == FieldSemanticFamily.ExternalCode;

            if (target.Target.NormalizedType == DvNormalizedType.String)
            {
                return source.Info.Family is FieldSemanticFamily.Core or FieldSemanticFamily.Name;
            }

            return source.Info.Family == FieldSemanticFamily.Core;
        }

        private static int GetLowConfidenceScore(TargetField target, SourceField source)
        {
            string targetName = target.Info.NormalizedName;
            string sourceName = source.Info.NormalizedName;

            bool contains =
                sourceName.Contains(targetName, StringComparison.Ordinal) ||
                targetName.Contains(sourceName, StringComparison.Ordinal);

            bool strippedContains =
                source.Info.StrippedNormalizedName.Contains(target.Info.StrippedNormalizedName, StringComparison.Ordinal) ||
                target.Info.StrippedNormalizedName.Contains(source.Info.StrippedNormalizedName, StringComparison.Ordinal);

            if (!contains && !strippedContains)
                return 0;

            int score = 55;

            if (source.Info.BaseName == target.Info.BaseName)
                score += 8;

            if (source.Info.Family == target.PreferredFamily)
                score += 5;

            if (strippedContains)
                score += 4;

            return Math.Min(score, 68);
        }

        private static string BuildSemanticReason(TargetField target)
        {
            if (target.Target.NormalizedType == DvNormalizedType.Guid)
            {
                return "UUID 目标优先：同基名字段中仅接受 *_dm/*_id/*_code 这类代码/标识字段";
            }

            return target.PreferredFamily switch
            {
                FieldSemanticFamily.Name => "名称语义优先：同基名字段中优先命中 *_mc/*_name/*_xm",
                FieldSemanticFamily.Description => "说明语义优先：同基名字段中优先命中 *_ms/*_desc/*_jc/*_yy/*_xx",
                FieldSemanticFamily.ExternalCode => "外部编码语义优先：同基名字段中优先命中 *_icd/*_icd10/*_icd9",
                FieldSemanticFamily.Identifier => "代码语义优先：同基名字段中优先命中 *_dm/*_id/*_code",
                _ => "同基名字段语义匹配"
            };
        }

        private static string BuildLowConfidenceReason(TargetField target)
        {
            return target.PreferredFamily switch
            {
                FieldSemanticFamily.Name => "模糊匹配：名称字段部分命中，建议确认",
                FieldSemanticFamily.Description => "模糊匹配：说明字段部分命中，建议确认",
                FieldSemanticFamily.ExternalCode => "模糊匹配：外部编码字段部分命中，建议确认",
                _ => "模糊匹配：字段名部分命中，建议确认"
            };
        }

        private static string BuildNoMatchReason(TargetField target, bool isAutoGen)
        {
            if (isAutoGen)
            {
                return "未匹配到源字段；该字段通常由系统自动生成，可按需忽略";
            }

            if (target.Target.NormalizedType == DvNormalizedType.Guid)
            {
                return "UUID 目标未找到兼容的代码/标识字段，已自动忽略";
            }

            return target.PreferredFamily switch
            {
                FieldSemanticFamily.Name => "未找到兼容的名称类源字段，已自动忽略",
                FieldSemanticFamily.Description => "未找到兼容的说明类源字段，已自动忽略",
                FieldSemanticFamily.ExternalCode => "未找到兼容的外部编码源字段，已自动忽略",
                _ => "未匹配到可用源字段"
            };
        }

        private static string BuildUuidManualReason(string reason, bool hasSuggestedSource)
        {
            string manualInstruction = hasSuggestedSource
                ? "UUID 字段不会自动确认，请人工核对后选择"
                : "UUID 字段请人工选择来源字段、固定值或忽略";

            return string.IsNullOrWhiteSpace(reason)
                ? manualInstruction
                : $"{reason}；{manualInstruction}";
        }

        private static bool IsAutoGeneratedUuidCandidate(
            DvTargetColumn target,
            IReadOnlyList<string> sourceHeaders,
            string? matchedSource)
        {
            if (target.NormalizedType != DvNormalizedType.Guid)
                return false;

            var targetInfo = AnalyzeField(target.ColumnName);
            string normalizedTarget = targetInfo.NormalizedName;
            bool isExplicitAutoGeneratedName =
                AutoGeneratedUuidNames.Contains(normalizedTarget, StringComparer.OrdinalIgnoreCase);
            bool looksLikeAutoGeneratedSuffix =
                targetInfo.Family == FieldSemanticFamily.Core &&
                AutoGeneratedUuidSuffixes.Any(suffix =>
                    normalizedTarget.Length > suffix.Length &&
                    normalizedTarget.EndsWith(suffix, StringComparison.OrdinalIgnoreCase));

            bool looksLikeAutoGeneratedId =
                isExplicitAutoGeneratedName || looksLikeAutoGeneratedSuffix;

            if (!looksLikeAutoGeneratedId)
                return false;

            var sameBaseSources = sourceHeaders
                .Select(AnalyzeField)
                .Where(info => info.BaseName == targetInfo.BaseName)
                .ToList();

            if (matchedSource != null)
            {
                var matchedInfo = AnalyzeField(matchedSource);
                if (!isExplicitAutoGeneratedName && matchedInfo.Family == FieldSemanticFamily.Identifier)
                    return false;
            }

            return sameBaseSources.All(info => info.Family == FieldSemanticFamily.Core);
        }

        private static FieldSemanticInfo AnalyzeField(string fieldName)
        {
            string lower = fieldName.ToLowerInvariant();
            string stripped = Strip(lower);
            string normalized = Normalize(lower);
            string strippedNormalized = Normalize(stripped);

            var semantic = TryAnalyzeSemantic(strippedNormalized);
            string baseName = semantic.BaseName.Length > 0
                ? semantic.BaseName
                : strippedNormalized;

            return new FieldSemanticInfo(
                fieldName,
                normalized,
                strippedNormalized,
                baseName,
                semantic.Family);
        }

        private static SemanticParseResult TryAnalyzeSemantic(string normalizedName)
        {
            foreach (var pattern in SemanticPatterns)
            {
                if (!normalizedName.EndsWith(pattern.Suffix, StringComparison.Ordinal))
                    continue;

                string baseName = normalizedName[..^pattern.Suffix.Length];
                if (string.IsNullOrWhiteSpace(baseName))
                    continue;

                return new SemanticParseResult(baseName, pattern.Family);
            }

            return new SemanticParseResult(normalizedName, FieldSemanticFamily.Core);
        }

        private static string Normalize(string value)
            => Regex.Replace(value.ToLowerInvariant(), @"[\-_\s]", "");

        private static string Strip(string value)
        {
            foreach (var prefix in DefaultPrefixes)
            {
                if (value.StartsWith(prefix, StringComparison.Ordinal))
                {
                    value = value[prefix.Length..];
                    break;
                }
            }

            foreach (var suffix in DefaultSuffixes)
            {
                if (value.EndsWith(suffix, StringComparison.Ordinal))
                {
                    value = value[..^suffix.Length];
                    break;
                }
            }

            return value;
        }

        private static readonly SemanticPattern[] SemanticPatterns =
        [
            new("icd10mc", FieldSemanticFamily.Name),
            new("icd9mc", FieldSemanticFamily.Name),
            new("icdmc", FieldSemanticFamily.Name),
            new("dmmc", FieldSemanticFamily.Name),
            new("icd10", FieldSemanticFamily.ExternalCode),
            new("icd9", FieldSemanticFamily.ExternalCode),
            new("icd", FieldSemanticFamily.ExternalCode),
            new("uuid", FieldSemanticFamily.Identifier),
            new("guid", FieldSemanticFamily.Identifier),
            new("code", FieldSemanticFamily.Identifier),
            new("name", FieldSemanticFamily.Name),
            new("desc", FieldSemanticFamily.Description),
            new("dm", FieldSemanticFamily.Identifier),
            new("id", FieldSemanticFamily.Identifier),
            new("mc", FieldSemanticFamily.Name),
            new("xm", FieldSemanticFamily.Name),
            new("ms", FieldSemanticFamily.Description),
            new("jc", FieldSemanticFamily.Description),
            new("yy", FieldSemanticFamily.Description),
            new("xx", FieldSemanticFamily.Description)
        ];

        private readonly record struct SemanticPattern(string Suffix, FieldSemanticFamily Family);

        private readonly record struct SemanticParseResult(string BaseName, FieldSemanticFamily Family);

        private readonly record struct SourceField(int Index, string Name, FieldSemanticInfo Info);

        private readonly record struct TargetField(
            int Index,
            DvTargetColumn Target,
            FieldSemanticInfo Info,
            FieldSemanticFamily PreferredFamily);

        private readonly record struct MatchDecision(
            string Source,
            DvMatchMethod Method,
            int Confidence,
            string Reason,
            bool NeedsConfirmation);

        private readonly record struct FieldSemanticInfo(
            string RawName,
            string NormalizedName,
            string StrippedNormalizedName,
            string BaseName,
            FieldSemanticFamily Family);

        private enum FieldSemanticFamily
        {
            Core,
            Identifier,
            Name,
            Description,
            ExternalCode
        }
    }
}
