using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;

namespace WpfApp1.Services
{
    public static class FieldMatcherService
    {
        private static readonly string[] DefaultPrefixes = ["zjb_", "tmp_", "mid_", "src_"];
        private static readonly string[] DefaultSuffixes = ["_text", "_str", "_value"];
        private static readonly string[] NameSuffixes = ["_mc", "_name"];
        private static readonly string[] CodeSuffixes = ["_dm", "_id", "_code"];
        private static readonly string[] AutoGeneratedUuidNames = ["id", "baid"];
        private static readonly string[] AutoGeneratedUuidSuffixes = ["id", "uuid", "guid"];

        /// <summary>Auto-generate field mapping suggestions.</summary>
        public static List<DvMappingRow> AutoMap(
            IReadOnlyList<DvTargetColumn> targets,
            IReadOnlyList<string> sourceHeaders)
        {
            var usedSources = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            var result = new List<DvMappingRow>();
            int rowIdx = 0;

            foreach (var target in targets)
            {
                var match = BestMatch(target, sourceHeaders, usedSources);

                rowIdx++;
                bool isAutoGen = IsAutoGeneratedUuidCandidate(target, sourceHeaders, match.Source);

                var row = new DvMappingRow
                {
                    RowIndex = rowIdx,
                    TargetColumnName = target.ColumnName,
                    TargetDisplayType = target.DisplayType,
                    IsRequired = !target.IsNullable,
                    IsAutoGenCandidate = isAutoGen
                };

                if (match.Source != null)
                {
                    row.MappingType = DvMappingType.Source;
                    row.SourceColumnName = match.Source;
                    row.MatchMethod = match.Method;
                    row.Confidence = match.Confidence;
                    row.MatchReason = match.Reason;
                    row.IsConfirmed = match.Method != DvMatchMethod.Contains;
                    row.NeedsConfirmation = match.Method == DvMatchMethod.Contains;
                    row.WasAutoIgnored = false;
                    usedSources.Add(match.Source);
                }
                else
                {
                    row.MappingType = DvMappingType.Ignore;
                    row.MatchMethod = DvMatchMethod.Manual;
                    row.Confidence = 0;
                    row.MatchReason = isAutoGen
                        ? "未匹配到源字段；该字段通常由系统自动生成，可按需忽略"
                        : "未匹配到可用源字段";
                    row.WasAutoIgnored = true;
                    row.IsConfirmed = isAutoGen || target.IsNullable;
                }

                result.Add(row);
            }

            return result;
        }

        private static MatchDecision BestMatch(
            DvTargetColumn target,
            IReadOnlyList<string> sources,
            HashSet<string> used)
        {
            var available = sources.Where(s => !used.Contains(s)).ToList();
            if (available.Count == 0)
            {
                return new MatchDecision(null, DvMatchMethod.Manual, 0, "没有剩余可用源字段");
            }

            string targetName = target.ColumnName;
            string tLower = targetName.ToLowerInvariant();
            string tNorm = Normalize(tLower);
            string tStripped = Strip(tLower);
            var targetMeaning = AnalyzeFieldMeaning(targetName);
            var preferredRole = InferPreferredRole(target, targetMeaning, available);
            var semanticCandidates = available
                .Select(source => new
                {
                    Source = source,
                    Meaning = AnalyzeFieldMeaning(source)
                })
                .Where(x =>
                    x.Meaning.BaseName == targetMeaning.BaseName &&
                    IsRoleCompatible(preferredRole, x.Meaning.Role))
                .OrderByDescending(x => GetSemanticMatchScore(preferredRole, x.Meaning.Role))
                .ThenBy(x => x.Source, StringComparer.OrdinalIgnoreCase)
                .ToList();

            if (ShouldPreferSemanticOverExact(target, targetMeaning, preferredRole))
            {
                var preferredSemantic = semanticCandidates
                    .FirstOrDefault(x => x.Meaning.Role == preferredRole);
                if (preferredSemantic != null)
                {
                    return new MatchDecision(
                        preferredSemantic.Source,
                        DvMatchMethod.PrefixStrip,
                        GetSemanticMatchScore(preferredRole, preferredSemantic.Meaning.Role),
                        GetSemanticMatchReason(target, preferredRole, preferredSemantic.Meaning.Role));
                }
            }

            foreach (var source in available)
            {
                if (string.Equals(source, targetName, StringComparison.OrdinalIgnoreCase))
                {
                    return new MatchDecision(source, DvMatchMethod.Exact, 100, "字段名完全一致");
                }
            }

            foreach (var source in available)
            {
                if (Normalize(source) == tNorm)
                {
                    return new MatchDecision(source, DvMatchMethod.Normalized, 90, "去除大小写和分隔符差异后命中");
                }
            }

            if (semanticCandidates.Count > 0)
            {
                var best = semanticCandidates[0];
                return new MatchDecision(
                    best.Source,
                    DvMatchMethod.PrefixStrip,
                    GetSemanticMatchScore(preferredRole, best.Meaning.Role),
                    GetSemanticMatchReason(target, preferredRole, best.Meaning.Role));
            }

            foreach (var source in available)
            {
                if (Strip(Normalize(source)) == tStripped)
                {
                    return new MatchDecision(source, DvMatchMethod.PrefixStrip, 75, "去掉常见前后缀后命中");
                }
            }

            var containsCandidates = available
                .Select(source => new
                {
                    Source = source,
                    Normalized = Normalize(source.ToLowerInvariant()),
                    Meaning = AnalyzeFieldMeaning(source)
                })
                .Where(x => x.Normalized.Contains(tNorm) || tNorm.Contains(x.Normalized))
                .OrderByDescending(x => GetContainsMatchScore(targetMeaning.BaseName, preferredRole, x.Meaning))
                .ThenBy(x => x.Source, StringComparer.OrdinalIgnoreCase)
                .ToList();

            if (containsCandidates.Count > 0)
            {
                var best = containsCandidates[0];
                return new MatchDecision(
                    best.Source,
                    DvMatchMethod.Contains,
                    GetContainsMatchScore(targetMeaning.BaseName, preferredRole, best.Meaning),
                    GetContainsMatchReason(target, targetMeaning.BaseName, preferredRole, best.Meaning));
            }

            return new MatchDecision(null, DvMatchMethod.Manual, 0, "未匹配到可用源字段");
        }

        private static bool IsAutoGeneratedUuidCandidate(
            DvTargetColumn target,
            IReadOnlyList<string> sourceHeaders,
            string? matchedSource)
        {
            if (target.NormalizedType != DvNormalizedType.Guid)
            {
                return false;
            }

            var targetMeaning = AnalyzeFieldMeaning(target.ColumnName);
            if (targetMeaning.Role != FieldSemanticRole.Neutral)
            {
                return false;
            }

            string normalizedTarget = Normalize(target.ColumnName);
            bool looksLikeAutoGeneratedId =
                AutoGeneratedUuidNames.Contains(normalizedTarget, StringComparer.OrdinalIgnoreCase) ||
                AutoGeneratedUuidSuffixes.Any(suffix =>
                    normalizedTarget.Length > suffix.Length &&
                    normalizedTarget.EndsWith(suffix, StringComparison.OrdinalIgnoreCase));

            if (!looksLikeAutoGeneratedId)
            {
                return false;
            }

            var sameBaseSources = sourceHeaders
                .Where(source => AnalyzeFieldMeaning(source).BaseName == targetMeaning.BaseName)
                .ToList();

            if (matchedSource != null)
            {
                var matchedMeaning = AnalyzeFieldMeaning(matchedSource);
                if (matchedMeaning.Role == FieldSemanticRole.Code)
                {
                    return false;
                }

                if (sameBaseSources.Any(source => AnalyzeFieldMeaning(source).Role == FieldSemanticRole.Code))
                {
                    return false;
                }
            }
            else if (sameBaseSources.Count > 0)
            {
                return false;
            }

            return true;
        }

        private static FieldMeaning AnalyzeFieldMeaning(string fieldName)
        {
            string stripped = Strip(fieldName.ToLowerInvariant());

            foreach (var suffix in NameSuffixes)
            {
                if (stripped.EndsWith(suffix, StringComparison.Ordinal))
                {
                    return new FieldMeaning(
                        Normalize(stripped[..^suffix.Length]),
                        FieldSemanticRole.Name);
                }
            }

            foreach (var suffix in CodeSuffixes)
            {
                if (stripped.EndsWith(suffix, StringComparison.Ordinal))
                {
                    return new FieldMeaning(
                        Normalize(stripped[..^suffix.Length]),
                        FieldSemanticRole.Code);
                }
            }

            return new FieldMeaning(Normalize(stripped), FieldSemanticRole.Neutral);
        }

        private static FieldSemanticRole InferPreferredRole(
            DvTargetColumn target,
            FieldMeaning targetMeaning,
            IReadOnlyList<string> availableSources)
        {
            if (targetMeaning.Role != FieldSemanticRole.Neutral)
            {
                return targetMeaning.Role;
            }

            bool hasNamePair = false;
            bool hasCodePair = false;

            foreach (var source in availableSources)
            {
                var sourceMeaning = AnalyzeFieldMeaning(source);
                if (sourceMeaning.BaseName != targetMeaning.BaseName)
                {
                    continue;
                }

                hasNamePair |= sourceMeaning.Role == FieldSemanticRole.Name;
                hasCodePair |= sourceMeaning.Role == FieldSemanticRole.Code;
            }

            if (!hasNamePair && !hasCodePair)
            {
                return FieldSemanticRole.Neutral;
            }

            if (target.NormalizedType == DvNormalizedType.Guid)
            {
                return FieldSemanticRole.Code;
            }

            if (target.NormalizedType == DvNormalizedType.String)
            {
                if (hasNamePair)
                {
                    return FieldSemanticRole.Name;
                }

                if (hasCodePair)
                {
                    return FieldSemanticRole.Code;
                }
            }

            return hasCodePair && !hasNamePair
                ? FieldSemanticRole.Code
                : FieldSemanticRole.Neutral;
        }

        private static bool IsRoleCompatible(FieldSemanticRole preferredRole, FieldSemanticRole candidateRole)
        {
            if (preferredRole == FieldSemanticRole.Neutral)
            {
                return true;
            }

            if (candidateRole == FieldSemanticRole.Neutral)
            {
                return true;
            }

            return preferredRole == candidateRole;
        }

        private static bool ShouldPreferSemanticOverExact(
            DvTargetColumn target,
            FieldMeaning targetMeaning,
            FieldSemanticRole preferredRole)
        {
            if (targetMeaning.Role != FieldSemanticRole.Neutral)
            {
                return false;
            }

            return target.NormalizedType == DvNormalizedType.Guid &&
                   preferredRole == FieldSemanticRole.Code;
        }

        private static int GetSemanticMatchScore(FieldSemanticRole preferredRole, FieldSemanticRole candidateRole)
        {
            if (preferredRole == FieldSemanticRole.Neutral)
            {
                return candidateRole == FieldSemanticRole.Neutral ? 80 : 78;
            }

            if (candidateRole == preferredRole)
            {
                return 85;
            }

            if (candidateRole == FieldSemanticRole.Neutral)
            {
                return 72;
            }

            return 0;
        }

        private static int GetContainsMatchScore(
            string targetBaseName,
            FieldSemanticRole preferredRole,
            FieldMeaning candidateMeaning)
        {
            int score = 50;

            if (candidateMeaning.BaseName == targetBaseName)
            {
                score += 20;
            }

            if (preferredRole != FieldSemanticRole.Neutral)
            {
                if (candidateMeaning.Role == preferredRole)
                {
                    score += 10;
                }
                else if (candidateMeaning.Role != FieldSemanticRole.Neutral)
                {
                    score -= 20;
                }
            }

            return score;
        }

        private static string GetSemanticMatchReason(
            DvTargetColumn target,
            FieldSemanticRole preferredRole,
            FieldSemanticRole candidateRole)
        {
            if (target.NormalizedType == DvNormalizedType.Guid &&
                preferredRole == FieldSemanticRole.Code &&
                candidateRole == FieldSemanticRole.Code)
            {
                return "UUID 目标优先：同基名字段中优先命中 *_dm/*_id/*_code";
            }

            if (preferredRole == FieldSemanticRole.Name && candidateRole == FieldSemanticRole.Name)
            {
                return "名称语义优先：同基名字段中优先命中 *_mc/*_name";
            }

            if (preferredRole == FieldSemanticRole.Code && candidateRole == FieldSemanticRole.Code)
            {
                return "代码语义优先：同基名字段中优先命中 *_dm/*_id/*_code";
            }

            return "同基名字段优先命中";
        }

        private static string GetContainsMatchReason(
            DvTargetColumn target,
            string targetBaseName,
            FieldSemanticRole preferredRole,
            FieldMeaning candidateMeaning)
        {
            if (candidateMeaning.BaseName == targetBaseName)
            {
                if (target.NormalizedType == DvNormalizedType.Guid &&
                    preferredRole == FieldSemanticRole.Code &&
                    candidateMeaning.Role == FieldSemanticRole.Code)
                {
                    return "模糊匹配：UUID 目标优先，建议确认 *_dm/*_id/*_code";
                }

                if (preferredRole == FieldSemanticRole.Name && candidateMeaning.Role == FieldSemanticRole.Name)
                {
                    return "模糊匹配：名称语义优先，建议确认";
                }

                if (preferredRole == FieldSemanticRole.Code && candidateMeaning.Role == FieldSemanticRole.Code)
                {
                    return "模糊匹配：代码语义优先，建议确认";
                }
            }

            return "模糊匹配：字段名部分命中，建议确认";
        }

        private static string Normalize(string s)
            => Regex.Replace(s.ToLowerInvariant(), @"[\-_\s]", "");

        private static string Strip(string s)
        {
            foreach (var prefix in DefaultPrefixes)
            {
                if (s.StartsWith(prefix, StringComparison.Ordinal))
                {
                    s = s[prefix.Length..];
                    break;
                }
            }

            foreach (var suffix in DefaultSuffixes)
            {
                if (s.EndsWith(suffix, StringComparison.Ordinal))
                {
                    s = s[..^suffix.Length];
                    break;
                }
            }

            return s;
        }

        private readonly record struct MatchDecision(string? Source, DvMatchMethod Method, int Confidence, string Reason);

        private readonly record struct FieldMeaning(string BaseName, FieldSemanticRole Role);

        private enum FieldSemanticRole
        {
            Neutral,
            Code,
            Name
        }
    }
}
